### ISSUE TITLE
Use this lib, but get true

### ISSUE THREAD

**Issue by sunfeng90** [jonschlinkert/has-values#2]
Hi, I set` nameObject = {}; hasValue(nameObject)`, but it console out true every time.

**Comment by doowb** [comment]
I'm not able to reproduce this with the code you posted. I'm assuming there's more to this than just the following:

```js
var hasValue = require('has-value');
var nameObject = {};
console.log(hasValue(nameObject));
```

**Comment by sunfeng90** [comment]
Thanks,I change another way to finish this, not to use your lib anymore.

**Comment by sunfeng90** [comment]
I solved it,thanks

     祝您及家人吉祥如意！

      此致

敬礼 ！

*                         孙峰*
*                         Feng Sun*

------------------------------------------------
小天鹅洗衣机事业部校园洗衣项目组
美的集团

*地 址*：上海市  浦东新区 张东路金秋路 科技领袖之都1387号 42幢 威灵研发中心 三楼
*E-Mail*: l <guanci_yang@163.com>uckysunfeng@gmail.com

2017-07-27 17:15 GMT+08:00 Jon Schlinkert <notifications@github.com>:
